sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"555555\"},{\"id\":8,
           \"username\":\"def\",\"password\":\"456\"},{\"id\":9,
           \"username\":\"eeee\",\"password\":\"789\"}]"
spring:
  application:
    name: user-service
  rabbitmq:
    host: 10.36.8.27
    port: 5672
    username: admin
    password: admin
server:
  port: 8101
#eureka 注册中心配置
eureka:
  client:
    service‐url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka


#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
